/**
 * Centralized Permission Matrix for BantuTepat RBAC.
 *
 * Defines which roles can perform which actions and is consumed by
 * rbac.middleware.js for route-level authorization.
 */

const ROLES = {
  ADMIN_MAIN: 'admin_main',
  ADMIN_STAFF: 'admin_staff',
  PENGAWAS: 'pengawas',
  RELAWAN: 'relawan',
  WARGA: 'warga',
};

const ALL_ROLES = Object.values(ROLES);
const ADMIN_ROLES = [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF];

const PERMISSIONS = {
  // User management
  USER_LIST: [ROLES.ADMIN_MAIN],
  USER_CREATE: [ROLES.ADMIN_MAIN],
  USER_UPDATE: [ROLES.ADMIN_MAIN],
  USER_DELETE: [ROLES.ADMIN_MAIN],
  USER_TOGGLE_ACTIVE: [ROLES.ADMIN_MAIN],

  // Household
  HOUSEHOLD_LIST: ALL_ROLES,
  HOUSEHOLD_CREATE: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN, ROLES.WARGA],
  HOUSEHOLD_UPDATE: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN, ROLES.WARGA],
  HOUSEHOLD_DELETE: [ROLES.ADMIN_MAIN],

  // Documents
  DOCUMENT_UPLOAD: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN, ROLES.WARGA],
  DOCUMENT_VERIFY: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  DOCUMENT_LIST: ALL_ROLES,

  // Aid applications
  APPLICATION_LIST_OWN: [ROLES.WARGA],
  APPLICATION_CREATE: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.WARGA],
  APPLICATION_LIST: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS],
  APPLICATION_DETAIL: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS, ROLES.WARGA],
  APPLICATION_SUBMIT: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.WARGA],
  APPLICATION_UPDATE_STATUS: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],

  // Beneficiary decisions
  DECISION_LIST: [ROLES.ADMIN_MAIN],
  DECISION_CREATE: [ROLES.ADMIN_MAIN],
  DECISION_UPDATE: [ROLES.ADMIN_MAIN],

  // Distributions
  DISTRIBUTION_LIST: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS],
  DISTRIBUTION_LIST_BASIC: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS, ROLES.RELAWAN],
  DISTRIBUTION_CREATE: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  DISTRIBUTION_UPDATE: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  DISTRIBUTION_PROOF_UPLOAD: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN],

  // Surveys
  SURVEY_LIST: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN],
  SURVEY_CREATE: [ROLES.RELAWAN],
  SURVEY_UPDATE: [ROLES.RELAWAN],

  // Complaints
  COMPLAINT_CREATE: [ROLES.WARGA],
  COMPLAINT_LIST_OWN: [ROLES.WARGA],
  COMPLAINT_LIST_ALL: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS],
  COMPLAINT_RESOLVE: [ROLES.ADMIN_MAIN],

  // Regions
  REGION_LIST: ADMIN_ROLES,
  REGION_CREATE: ADMIN_ROLES,
  REGION_UPDATE: ADMIN_ROLES,
  REGION_DELETE: [ROLES.ADMIN_MAIN],

  // Aid types
  AID_TYPE_LIST: ADMIN_ROLES,
  AID_TYPE_CREATE: ADMIN_ROLES,
  AID_TYPE_UPDATE: ADMIN_ROLES,
  AID_TYPE_DELETE: [ROLES.ADMIN_MAIN],

  // Audit logs
  AUDIT_LOG_FULL: [ROLES.ADMIN_MAIN, ROLES.PENGAWAS],
  AUDIT_LOG_LIMITED: [],

  // Dashboard
  DASHBOARD_OVERVIEW: [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.PENGAWAS],
  DASHBOARD_ADMIN: ADMIN_ROLES,
  DASHBOARD_OWN: ALL_ROLES,

  // Monitoring tools
  USER_ACTIVITY_VIEW: [ROLES.ADMIN_MAIN],
  DATA_VALIDATION_VIEW: ADMIN_ROLES,

  // Warga account creation
  WARGA_ACCOUNT_CREATE: [ROLES.ADMIN_MAIN],
};

const APPLICATION_TRANSITIONS = {
  'draft→submitted': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.WARGA],
  'submitted→initial_validation': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  'initial_validation→document_verification': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  'document_verification→field_survey': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  'field_survey→scoring': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  'scoring→admin_review': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF],
  'admin_review→approved': [ROLES.ADMIN_MAIN],
  'admin_review→rejected': [ROLES.ADMIN_MAIN],
  'submitted→cancelled': [ROLES.ADMIN_MAIN, ROLES.WARGA],
};

const DISTRIBUTION_TRANSITIONS = {
  'recorded→allocated': ADMIN_ROLES,
  'allocated→sent': ADMIN_ROLES,
  'sent→delivered': [ROLES.ADMIN_MAIN, ROLES.ADMIN_STAFF, ROLES.RELAWAN],
  'delivered→completed': ADMIN_ROLES,
  'allocated→failed': ADMIN_ROLES,
  'sent→failed': ADMIN_ROLES,
};

module.exports = {
  ROLES,
  ALL_ROLES,
  ADMIN_ROLES,
  PERMISSIONS,
  APPLICATION_TRANSITIONS,
  DISTRIBUTION_TRANSITIONS,
};
